version: '3.9'

services:
  app:
    image: ghcr.io/iamprompt/wheel-go-app-site:latest
    container_name: app
    restart: always
    ports:
      - 8080:80
    networks:
      - iamprompt

  admin:
    image: ghcr.io/iamprompt/wheel-go-admin:latest
    container_name: admin
    restart: always
    ports:
      - 8081:3000
    networks:
      - iamprompt

  payload:
    image: ghcr.io/iamprompt/wheel-go-payload:latest
    container_name: payload
    restart: always
    ports:
      - 8082:3000
    environment:
      - MONGODB_URI=mongodb://root:root@mongo:27017/wheel-go-payload?authSource=admin
      - PAYLOAD_SECRET=${PAYLOAD_SECRET:-secret}
      - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL}
    networks:
      - iamprompt

  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: wheel-go-payload
    networks:
      - iamprompt

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - iamprompt

volumes:
  data:

networks:
  iamprompt:
