version: '3.9'

services:
  app:
    image: wheel-go/app:latest
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    container_name: app
    restart: always
    ports:
      - 8080:80

  admin:
    image: wheel-go/admin:latest
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    container_name: admin
    restart: always
    ports:
      - 8081:3000

  payload:
    image: wheel-go/payload:latest
    build:
      context: .
      dockerfile: ./apps/payload/Dockerfile
      args:
        - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL:-http://localhost:8082}
    container_name: payload
    restart: always
    ports:
      - 8082:3000
    environment:
      - MONGODB_URI=mongodb://root:root@mongo/wheel-go-payload?authSource=admin
      - PAYLOAD_SECRET=fa03dcbff331d674352b8399
      - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL:-http://localhost:8082}

  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: wheel-go-payload

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  data:
