export enum PLACE_TYPES {
  BUILDING = 'BUILDING',
  TRANSPORT = 'TRANSPORT',
  CAFE = 'CAFE',
  FOOD = 'FOOD',
  TOILET = 'TOILET',
  PARK = 'PARK',
  RESIDENCE = 'RESIDENCE',
  PARKING = 'PARKING',
  CURBCUT = 'CURBCUT',
  SPORT = 'SPORT',
}
