name: Deploy App APK Debug Preview

on:
  push:
    branches:
      - main
    paths:
      - apps/app/**
      - packages/**
      - .github/workflows/build-app-apk.yaml
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build App Debug APK
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build APK
        run: pnpm --filter @wheel-go/app build:android --no-open

      - name: Generate APK
        working-directory: ./apps/app/android/
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: wheel-go-debug
          path: ./apps/app/android/app/build/outputs/apk/debug/app-debug.apk
